language: r
r: bioc-release
r: bioc-devel

cache: packages

before_install:
  - tlmgr install tcolorbox
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

# safelist
branches:
  only:
  - master
  - development

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"
warnings_are_errors: false
